[package]
name = "common-crypto"
version = "0.1.0"
authors = ["Muta Dev <muta@nervos.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ophelia-bls12381 = { git = "https://github.com/zeroqn/ophelia.git", features = [ "generate" ] }
ophelia-secp256k1 = { git = "https://github.com/zeroqn/ophelia.git" }
ophelia = { git = "https://github.com/zeroqn/ophelia.git" }

[features]
default = ["generate"]
generate = ["ophelia-secp256k1/generate", "ophelia/generate"]
